on: push

jobs:
  loop-through-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Repo
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |  
          response=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/zongzhenjiang/Test)
          if [ "$response" -eq 200 ]; then
            echo "Repository exists."
          elif [ "$response" -eq 404 ]; then
            echo "Repository does not exist."
          else
            echo "Error: Unable to check repository status."
          fi