on: push

jobs:
    loop-through-projects:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v2
  
        - name: Loop
          run: |
            # 进入目标文件夹
            for dir in webs/*; do
                git diff --quiet HEAD -- "$dir"
                change=$?
                if [ $change -eq 0 ]; then
                    echo "$dir no change"
                else
                    echo "$dir has change"
                fi
            done