on: push

jobs:
  loop-through-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Repo
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -d '{"name":"new-repository-name", "private":true}' \
            https://api.github.com/user/repos