on: push

jobs:
    loop-through-projects:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v2
            
        - name: Fetch previous commit
          run: |
                git fetch origin main
                
        - name: Loop
          run: |
                if git diff --quiet HEAD^ HEAD -- webs/; then
                    echo "No changes in webs/ directory"
                else
                    echo "Changes detected in webs/ directory"
                fi
