on: push

jobs:
    loop-through-projects:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        
        - name: Install dependencies
          run: |
            npm install -g pnpm@latest-10
            pnpm --version
        
        - name: Loop through files in a directory
          run: |
            files=()
            for dir in webs/*; do
              if [ -d "$dir" ]; then
                echo "Directory: $dir"
                if git diff --quiet HEAD^ HEAD -- "$dir"; then
                  echo "No changes."
                else
                  files+=("$dir")
                  echo "Changes detected."
                fi
              fi
            done
            echo "files=${files[@]}" >> $GITHUB_ENV

        - name: Login
          uses: docker/login-action@v3
          with: 
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build And Push Changed Project
          run: |
            # Retrieve the files from the environment variable
            echo "Files from previous step: $files"

            # Do something with the files and list them
            for file in $files; do
              echo "Processing file: $file"
              cd "$file"
              pnpm install
              pnpm run build
              NAME=$(jq -r .name package.json)
              VERSION=$(jq -r .version package.json)
              echo "$NAME $VERSION"
              docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/$NAME:$VERSION .
            done